### ISSUE TITLE
Add ability to re-run last test

### ISSUE THREAD

**Issue by axelson** [ananthakumaran/exunit.el#1]
It would be really nice to have a command like `exunit-verify-rerun-last-test` that would re-run the last test that was ran. Ideally for me this would re-run it from the same directory that it ran from previously and would be projectile aware (although that might be overkill).

Thanks for this project! It's very helpful.

**Comment by ananthakumaran** [comment]
exunit uses the compilation-mode, so it supports all the features supported by complication-mode. You could use `g` from the compilation buffer to re-run. I always use this, that's why never found the need to add one in exunit itself.

Another person had asked me the same thing, so we could consider adding the command in exunit itself.

**Comment by ananthakumaran** [comment]
Added `exunit-rerun` in the master, let me know if anything doesn't work as expected

**Comment by axelson** [comment]
Thanks! I'll check it out and let you know

**Comment by axelson** [comment]
Thanks! This is fantastic and works basically exactly as I want/expect it to. Already a huge improvement over my previous setup. :)
